<!DOCTYPE HTML>
<html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>Twitter Followers</title>
      <script language="javascript" src="/js/jquery.min-v1.js"></script>
      <link type="text/css" rel="stylesheet" media="screen" href="/css/main-v1.css"/>
    </head>
    <body>
        <div class="wrapper">
            <?php echo $this->layout()->content;?>
        </div>
    </body>
</html>
