<?php 
if ($this->pageCount): ?> 
<div class="pagination" style="width:100%">
    <div style="margin-top:10px;float:right;">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
              <a href="javascript:void(0);" onclick="getFollowerDetails('<?php echo $this->previous;?>','<?php echo $this->twitterhandle;?>','');return false;">&lt; Previous</a> |
        <?php else: ?>
            <span class="disabled">&lt; Previous</span> |
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page):?>
            <?php if ($page != $this->current): ?>
                <a href="javascript:void(0);" onclick="getFollowerDetails('<?php echo $page;?>','<?php echo $this->twitterhandle;?>','<?php echo ((($page == $this->pageCount) && $this->nextCursor != 0)?$this->nextCursor:'');?>');return false;"><?php echo $page;?></a>
            <?php else: ?>
                <?php echo $page; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if ((isset($this->next)) || (($this->next == $this->pageCount) && $this->nextCursor != 0)): ?>
              | <a href="javascript:void(0);" onclick="getFollowerDetails('<?php echo $this->next;?>','<?php echo $this->twitterhandle;?>','<?php echo ((($this->next == $this->pageCount) && $this->nextCursor != 0)?$this->nextCursor:'');?>');return false;">Next &gt;</a> |
        <?php else: ?>
            | <span class="disabled">Next &gt;</span> |
        <?php endif; ?>
    </div>
 </div>
<?php endif; ?>
